import { Nunito } from "next/font/google";
import "./globals.css";
import ClientOnly from "./ClientOnly";
import Navbar from "./components/navbar/Navbar";
import MantineProvider from "./MantineProvider";

export const metadata = {
  title: "Bon Appetit",
  description: "Generated by create next app",
};

const font = Nunito({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <MantineProvider>
          <Navbar />

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
